name: CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CodeStyle:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
         sudo apt update 
         sudo apt install -y python3-pip
         pip3 install flake8
      - name: Codestyle
        run: python3 -m flake8 ./ --ignore=F401,E402
  
  Tests:
    runs-on: self-hosted
    needs: CodeStyle
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: |
          pip install -e '.[test]'
          python3 -m coverage run -m pytest
          python3 -m coverage report
          
          
  Deploy:
    runs-on: self-hosted
    needs: Tests
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: "calculatormichail" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          
  TelegramNotifications:
    runs-on: self-hosted
    needs: Deploy
    steps:
      - name: NotificationFailure
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ❌ error
      
      - name: NotificationSuccess
        uses: appleboy/telegram-action@master
        if: success()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ✅ !!Success!! ✅
      
